baseURL = 'https://redsportsbetting.pages.dev/'
languageCode = 'en-us'
title = 'VSB1 - Virtual Sports Betting'
theme = 'ananke'

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Matches"
  url = "/matches/"
  weight = 2

[[menu.main]]
  name = "Leaderboard"
  url = "/leaderboard/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "Profile"
  url = "/profile/"
  weight = 5

[[menu.main]]
  name = "My Bets"
  url = "/my-bets/"
  weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true